config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    post 'sign_in', to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'users/edit', to: 'home#user_edit', as: 'edit_user_registration'
    patch 'users', to: 'users/registrations#update', as: 'user_registration'
  end

  root to: 'home#index'
  resources :tasks
  resources :comments
  get 'my_tasks', to: 'home#my_tasks'
  post 'create_project_user_task', to: 'home#create_project_user_task'
  get 'project_details', to: 'home#project_details'
  delete 'profile_picture', to: 'home#profile_picture'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home controller
class HomeController < ApplicationController
  before_action :authenticate_current_user!
  def index; end

  def user_edit
    respond_to do |format|
      format.js
    end
  end

  def my_tasks
    @projects = current_user.projects
    @tasks = {}

    @projects.each do |project|
      user_tasks = ProjectUser.get_project_user(current_user.id, project.id)
                              .tasks
      @tasks.merge!(project.name.to_sym => user_tasks) unless user_tasks.empty?
    end
  end

  def create_project_user_task
    user_id = params[:project_user][:user_id]
    project_id = params[:project]
    @project_user = ProjectUser.get_project_user(user_id, project_id) # scoped

    if @project_user.nil?
      @project_user = ProjectUser.new(user_id: user_id, project_id: project_id,
                                      assigned_by: current_user.id,
                                      designation: :DEV)
    end
    @project_user.tasks.build(task_params)
    send_create_response
  end

  def send_create_response
    if @project_user.save
      project_user = @project_user.as_json(
        include: { user: { only: :email }, assigner: { only: :email } },
        only: :designation
      )
      task = Task.last.as_json(only: %i[id name status end_date start_date])
      render json: { status: 200, task: task, project_user: project_user }
    else
      render json: { status: 400, error: @project_user.errors }
    end
  end

  def profile_picture
    current_user.profile_picture.purge
    redirect_to root_path
  end

  def project_details
    set_project_data
    respond_to do |format|
      format.js
    end
  end

  private

  def set_project_data
    @project = Project.find(params[:project])
    @users = users_for_assigning_task
    @role = user_role

    @projectuser = ProjectUser.new
    @projectuser.project_id = @project.id
    @tasks = project_tasks
    @task = Task.new
  end

  def project_tasks
    Task.joins(:project_user).where(project_users: { project_id: @project.id })
  end

  def users_for_assigning_task
    pm = @project.project_users.PM.pluck(:user_id) # gives current projects PM
    User.employee.where.not(id: pm)
  end

  def user_role
    ProjectUser.get_project_user(current_user.id, @project.id).designation
  end

  def task_params
    params.require(:project_user).require(:task).permit(:name, :start_date,
                                                        :end_date, :status)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_add_task.html.erb
<!-- Button trigger modal -->
<% @role == 'PM' ? style= 'display:block' : style = 'display:none' %>


<button type="button" id="add_task" style=<%= style %> class="btn btn-primary " data-toggle="modal" data-target="#exampleModalCenter">
Add Task
</button>

<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <%= form_for(@projectuser, url: create_project_user_task_path, html: { method: :post, class: 'task_form'} ) do |f| %>
        <div class="field form-group">
          <%= f.label :user_id %><br />
          <% if @role == 'PM' %>
            <select class="myselect form-control" name="project_user[user_id]" style="width:500px;">
          <% else %>
            <select class="myselect form-control" name="project_user[user_id]" style="width:500px;" disabled>
          <% end %>
              <% @users.each do |user| %>
                <option value="<%= user.id %>"><%= user.email %></option>
              <% end %>
            </select>
        </div>
          <%= hidden_field_tag 'project', @project.id %>
          <%= f.fields_for @task do |ff| %>
            <p style="color:red" id="task_name_error"></p>

            <div class="field form-group">
              <%= ff.label :name %><br />
              <%= ff.text_field :name, autofocus: true,class:"form-control", disabled: @role == 'PM' ? false : true %>
            </div>

            <div class="field form-group">
              <%= ff.label :status %><br />
              <%= ff.select :status, options_for_select(['Not_Started','In_Progress','Done']), autofocus: true,class:"form-control" %>
            </div>

            <p style="color:red" id="task_start_date_error"></p>

            <div class="field form-group">
              <%= ff.label :start_date %><br />
              <%= ff.text_field :start_date, 'data-provide':'datepicker',class:"form-control datepicker"  %>
            </div>

            <p style="color:red" id="task_end_date_error"></p>

            <div class="field form-group">
              <%= ff.label :end_date %><br />
              <%= ff.text_field :end_date, 'data-provide':'datepicker',class:"form-control datepicker"  %>
            </div>

          <% end %>

          <div class="actions">
            <button type="button" name="task_update" class="btn btn-primary" id="task_update" style="display:none;">Update</button>
            <%= f.submit 'Submit', class:"btn btn-primary", id:"task_submit", data: { disable_with: false } %>
          </div>





        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close_modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_edit.html.erb
  <h3>Edit User</h3>
  <%= form_for(resource, url: user_registration_path, html: { method: :patch }) do |f| %>
    <%= devise_error_messages! %>

    <div class="field form-group">
      <%= f.label :profile_picture %><br />
      <%= f.file_field :profile_picture, autofocus: true,class:"form-control" %>
      <% if current_user.profile_picture.attached? %>
      <%=image_tag(current_user.profile_picture.variant(resize: "56x56")) %>
      <%= link_to 'Remove', profile_picture_path,
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
                <% end %>
    </div>

    <div class="field form-group">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, autofocus: true,class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, autofocus: true,class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email",class:"form-control" %>
    </div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>

    <div class="field form-group">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "new-password",class:"form-control" %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password",class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "current-password",class:"form-control" %>
    </div>

    <div class="actions">
      <%= f.submit "Update",class:"btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to "Back", :back %>

app/views/home/_my_tasks.html.erb
<div class="jumbotron">
  <h1 style="text-align:center"> My Tasks</h1>
</div>
<div class="">
  <% if @tasks.empty? %>
    <h3> No Pending Tasks</h3>
  <% end %>
</div>
<div id="accordion">
  <% project_names = @tasks.keys %>
  <% project_names.each do |project_name| %>
  <div class="card">
    <div class="card-header" id="heading<%= project_name%>">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapse<%= project_name%>" aria-expanded="true" aria-controls="collapseOne">
          <%= project_name %>
        </button>
      </h5>
    </div>

    <div id="collapse<%= project_name%>" class="collapse" aria-labelledby="heading<%= project_name%>" data-parent="#accordion">
      <div class="card-body" id="project_<%= project_name %>">
        <%= render partial: "home/table", locals: { tasks: @tasks[project_name] } %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/home/_project_contents.html.erb
<div class="jumbotron">
  <h1 style="text-align:center">Project : <%= @project.name %></h1>
</div>
<div class="table-responsive">
  <%= render partial: "home/table", locals: { tasks: @tasks } %>
</div>

  <%= render partial: "home/add_task" %>

app/views/home/_table.html.erb
<% @role == 'PM' ? style = 'display:block' : style = 'display:none' %>
<table class="table table-hover table-dark">
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Assigned to</th>
    <th scope="col">Assigned by</th>
    <th scope="col">Designation</th>
    <th scope="col">Status</th>
    <th scope="col">Start Date</th>
    <th scope="col">End Date</th>
    <th scope="col">Edit</th>
  </tr>
</thead>
<tbody>
  <% tasks.each_with_index do |task, index| %>
      <tr id=row<%= task.id %> >
        <td ><%= index+1 %></td>
        <td><%= task.name %></td>
        <td><%= task.project_user.user.email %></td>
        <td><%= task.project_user.assigner.email %></td>
        <td><%= task.project_user.designation %></td>
        <td><%= task.status %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date%></td>
        <% if @role == 'PM' %>
          <td> <a class ="edit" id=<%= task.id %> href="#" >edit</a> <a class ="delete" id=<%= task.id %> href="#" >delete</a> <a class ="view" class="view" id=<%= task.id %> href="#" >view</a></td>
        <% elsif task.project_user.user == current_user %>
          <td> <a class ="edit" id=<%= task.id %> href="#" >edit</a>  <a class ="view" class="view" id=<%= task.id %> href="#" >view</a></td>
        <% else %>
          <td><a class ="view" class="view" id=<%= task.id %> href="#" >view</a></td>
        <% end %>
    </tr>
  <% end %>
</tbody>
</table>

app/views/home/my_tasks.js.erb
$('#main_page').html("<%= j render(:partial => 'home/my_tasks') %>");

app/views/home/project_details.js.erb
$('#main_page').html("<%= j render(:partial => 'home/project_contents') %>");

app/views/home/project_user_task.js.erb
<% if  @project_user.errors.messages %>
  $('#task_error').html("<%= @project_user.errors.messages.first %>")
  console.log("<%= @project_user.errors.messages.first %>");
<% end %>

app/views/home/user_edit.js.erb
$('#main_page').html("<%= j render(:partial => 'home/edit') %>");