config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    post 'sign_in', to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'users/edit', to: 'home#user_edit', as: 'edit_user_registration'
    patch 'users', to: 'users/registrations#update', as: 'user_registration'
  end

  root to: 'home#index'
  resources :tasks
  resources :comments
  get 'my_tasks', to: 'home#my_tasks'
  post 'create_project_user_task', to: 'home#create_project_user_task'
  get 'project_details', to: 'home#project_details'
  delete 'profile_picture', to: 'home#profile_picture'
end

app/views/layouts/_sidebar.html.erb
<div class="page-wrapper chiller-theme toggled">
  <div id="show-sidebar" class="btn btn-sm btn-dark" >
    <i class="fas fa-bars"></i>
  </div>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a>Task Manager</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
            <%= if current_user.profile_picture.attached?
              link_to image_tag(current_user.profile_picture.variant(resize: "56x56")), current_user.profile_picture
            else
              image_tag('user.jpg')
            end %>
        </div>
        <div class="user-info">
          <span class="user-name"><%= current_user.first_name %>
            <strong><%= current_user.last_name %></strong>
          </span>
          <span class="user-role">Employee</span>
          <span class="user-status">
            <span><%= current_user.email %></span>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>Projects</span>
          </li>
          <li class="sidebar">
            <%= link_to my_tasks_path, remote: true do %>
            <i class="fa fa-book"></i><span>My Tasks</span>
            <% end %>
          </li>
          <li class="sidebar-dropdown">
            <a>
              <i class="fa fa-shopping-cart"></i>
              <span>My Projects</span>

            </a>
            <div class="sidebar-submenu">
              <ul>
                <% current_user.projects.each do |project| %>
                  <li>
                    <%= link_to  project.name,project_details_url(project:project), remote: true %>
                  </li>
                <% end %>
              </ul>
            </div>
          </li>


          <li class="header-menu">
            <span>Settings</span>
          </li>



          <li>
            <a id="edit_user">
              <i class="fas fa-user"></i>
              <span>Edit user</span>
            </a>
          </li>

          <li>
            <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/users">
              <i class="fas fa-trash-alt"></i>
              <span>Cancel account</span>
            </a>
          </li>
          <li>
            <a rel="nofollow" data-method="delete" href="/sign_out">
              <i class="fas fa-sign-out-alt"></i>
              <span>Sign out</span>
            </a>
          </li>

        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->

  </nav>
  <!-- sidebar-wrapper  -->
  <main class="page-content">
    <div class="container-fluid" id="main_page">
<%= yield %>
    </div>

  </main>
  <!-- page-content" -->


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  </head>
  <body>
    <% if current_user.nil? %>
      <%= yield %>
    <% else %>
      <%= render partial: "layouts/sidebar" %>
    <% end %>
  </body>
</html>